# Generated by Django 6.0 on 2025-12-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_user_address_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_Iajzp-onUeDOfrpk3zO0QNPzIXXoEBCWXw&s')),
                ('cusine', models.CharField(max_length=200)),
                ('rating', models.FloatField(max_length=20)),
            ],
        ),
    ]
